on:
  push: # run when commits are pushed

env:
  default-python: "3.10"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.default-python }}

      - name: Install dependencies
        run: |
          pipx install poetry nox
          pipx inject poetry poetry-plugin-export
      - name: Run nox
        run: |
          nox --error-on-missing-interpreters --non-interactive
